In [7]:
# 期望不变 ->保持模型平滑，如果期望变小，很有可能所有参数变大，期望是线性的，和单层输出一致
import torch
from torch import nn
from d2l import torch as d2l

def dropout_layer (X,dropout):   #X为dropout层的输入，dropout为设置的丢弃概率
    assert 0<=dropout<=1        #丢弃概率介于0，1之间
    if dropout == 1:
       return torch.zeros_like(X) #若丢弃概率为1，则X的全部项均被置0
    if dropout == 0:
       return X                   #若丢弃概率为0，不对X作丢弃操作，直接返回X
    mask=(torch.Tensor(X.shape).uniform_(0,1)>dropout).float() #用uniform函数生成0-1间的随机实数，利用”>"，将大于dropout的记为1，小于dropout的记为0，实现丢弃操作
    return mask*X/(1-dropout) #将mask与X相乘实现丢弃操作，并除以(1-dropout)，这里不使用选中X中元素置0的原因是相乘操作相比选中操作更快

In [8]:
#丢弃法测试
X=torch.arange(16,dtype=torch.float32).reshape((2,8))
print(X)
print(dropout_layer (X,0.))  #丢弃率设置为0
print(dropout_layer (X,0.5)) #丢弃率设置为0.5
print(dropout_layer (X,1))   #丢弃率设置为1


tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0., 14.],
        [ 0., 18.,  0.,  0., 24.,  0.,  0., 30.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])


In [ ]:
# 训练的时候dropout Net(is_training = True)
# 测试的时候不dropout
# loss = nn.CrossEntropyLoss()
#

In [10]:
net = nn.Sequential(
    nn.Flatten(),nn.Linear(784,256),nn.ReLU(),
    nn.Dropout1(dropout1),nn.Linear(256,256),nn.ReLU(),
    nn.Dropout2(dropout2),nn.Linear(256,10)
)
#最主流多层感知机的控制

AttributeError: module 'torch.nn' has no attribute 'Dropout1'