In [3]:
import torch

In [4]:

x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
x[3]

tensor(3)

In [7]:
len(x)

4

In [6]:
x.shape

torch.Size([4])

In [8]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [9]:
A = A.T
A

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [11]:
B = torch.tensor(([1,2],[2,1]))
B == B.T
# 答案bool向量

tensor([[True, True],
        [True, True]])

In [14]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [15]:
C = X.clone() # 复制tensor

In [16]:
C

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [17]:
X, X + C

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]))

In [19]:
C * X #哈达马积 每个对应元素相乘 非矩阵乘法 必须要形状一样

tensor([[[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121]],

        [[144, 169, 196, 225],
         [256, 289, 324, 361],
         [400, 441, 484, 529]]])

In [24]:
X.sum() #标量
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [22]:
A_sum_axis0 = X.sum(axis = 0)
A_sum_axis0

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])

In [25]:
X.sum(axis = [0,1])#axis里面向量作为index求和

tensor([60, 66, 72, 78])

In [26]:
X.sum(axis = 1)

tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])

In [27]:
X.sum(axis = [1,2])

tensor([ 66, 210])

In [38]:
X = X.float()
X.mean(axis = 0)

TypeError: 'torch.Size' object is not callable

In [39]:
X.cumsum(axis = 0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]])

In [56]:
#点积
A = torch.arange(12,dtype = torch.float32).reshape(3,4)
B = torch.arange(12,dtype = torch.float32).reshape(4,3)
y = torch.ones(4,dtype = torch.float32)
y = y.T
x = torch.ones(4,dtype = torch.float32)
A , y , torch.mv(A,y) #矩阵 . 向量点乘积


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([1., 1., 1., 1.]),
 tensor([ 6., 22., 38.]))

In [57]:
A,B , torch.mm(A,B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]),
 tensor([[ 42.,  48.,  54.],
         [114., 136., 158.],
         [186., 224., 262.]]))

In [58]:
#向量L2范数 即F
u = torch.tensor([3.0,-4.0])
torch.norm(uuu)

tensor(5.)

In [59]:
#同理，矩阵F范数
torch.norm(torch.ones(4,9))
# sqrt(∑xij^2)

tensor(6.)

In [ ]:
# 矩阵求导数
#梯度和等高线正交 

In [ ]:
#自动求导


In [ ]:
#1.计算图 -> 树类结构 tensorflow
#最底部的节点是基本向量矩阵
#每一层都代表一个基本计算：内积，乘积，加减法

In [64]:
!conda install mxnet
from mxnet import sym 

Channels:
 - defaults
Platform: win-64
Solving environment: ...working... failed



LibMambaUnsatisfiableError: Encountered problems while solving:
  - package mxnet-1.2.1-h8cc8929_0 requires py-mxnet 1.2.1.*, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ mxnet =* * is installable with the potential options
│  ├─ mxnet 1.1.0 would require
│  │  └─ python >=3.5,<3.6.0a0 *, which can be installed;
│  ├─ mxnet 1.1.0 would require
│  │  └─ python >=3.6,<3.7.0a0 *, which can be installed;
│  └─ mxnet 1.2.1 would require
│     └─ py-mxnet =1.2.1 * with the potential options
│        ├─ py-mxnet 1.2.1 would require
│        │  └─ python >=3.5,<3.6.0a0 *, which can be installed;
│        └─ py-mxnet 1.2.1 would require
│           └─ python >=3.6,<3.7.0a0 *, which can be installed;
└─ pin on python 3.12.* =* * is not installable because it requires
   └─ python =3.12 *, which conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned sp

ModuleNotFoundError: No module named 'mxnet'

In [60]:
a = sym.var()
b = sym.var()
c = 2*a + b

NameError: name 'sym' is not defined